[2024-02-21 05:34:09,651] {processor.py:153} INFO - Started process (PID=5235) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:34:09,652] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:34:09,653] {logging_mixin.py:115} INFO - [2024-02-21 05:34:09,652] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:34:09,658] {logging_mixin.py:115} INFO - [2024-02-21 05:34:09,658] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/tests/test_models.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/test_models.py", line 1, in <module>
    from part1.airflow_local.dags.models import URLClass
ModuleNotFoundError: No module named 'part1'
[2024-02-21 05:34:09,659] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:34:09,675] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.026 seconds
[2024-02-21 05:34:31,684] {processor.py:153} INFO - Started process (PID=5276) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:34:31,687] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:34:31,688] {logging_mixin.py:115} INFO - [2024-02-21 05:34:31,688] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:34:31,700] {logging_mixin.py:115} INFO - [2024-02-21 05:34:31,699] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/tests/test_models.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/test_models.py", line 1, in <module>
    from airflow_local.dags.models import URLClass
ModuleNotFoundError: No module named 'airflow_local'
[2024-02-21 05:34:31,701] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:34:31,727] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.048 seconds
[2024-02-21 05:35:02,486] {processor.py:153} INFO - Started process (PID=5330) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:35:02,487] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:35:02,488] {logging_mixin.py:115} INFO - [2024-02-21 05:35:02,488] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:35:02,495] {logging_mixin.py:115} INFO - [2024-02-21 05:35:02,493] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/tests/test_models.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/test_models.py", line 1, in <module>
    from airflow_local.dags.models import URLClass
ModuleNotFoundError: No module named 'airflow_local'
[2024-02-21 05:35:02,495] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:35:02,519] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.038 seconds
[2024-02-21 05:35:33,209] {processor.py:153} INFO - Started process (PID=5393) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:35:33,210] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:35:33,211] {logging_mixin.py:115} INFO - [2024-02-21 05:35:33,211] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:35:33,218] {logging_mixin.py:115} INFO - [2024-02-21 05:35:33,217] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/tests/test_models.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/test_models.py", line 1, in <module>
    from airflow_local.dags.models import URLClass
ModuleNotFoundError: No module named 'airflow_local'
[2024-02-21 05:35:33,219] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:35:33,247] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.044 seconds
[2024-02-21 05:36:04,074] {processor.py:153} INFO - Started process (PID=5456) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:36:04,076] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:36:04,078] {logging_mixin.py:115} INFO - [2024-02-21 05:36:04,077] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:36:04,088] {logging_mixin.py:115} INFO - [2024-02-21 05:36:04,086] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/tests/test_models.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/test_models.py", line 1, in <module>
    from airflow_local.dags.models import URLClass
ModuleNotFoundError: No module named 'airflow_local'
[2024-02-21 05:36:04,089] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:36:04,127] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.060 seconds
[2024-02-21 05:36:34,698] {processor.py:153} INFO - Started process (PID=5519) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:36:34,700] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:36:34,702] {logging_mixin.py:115} INFO - [2024-02-21 05:36:34,702] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:36:34,711] {logging_mixin.py:115} INFO - [2024-02-21 05:36:34,710] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/tests/test_models.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/test_models.py", line 1, in <module>
    from airflow_local.dags.models import URLClass
ModuleNotFoundError: No module named 'airflow_local'
[2024-02-21 05:36:34,712] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:36:34,737] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.048 seconds
[2024-02-21 05:37:00,233] {processor.py:153} INFO - Started process (PID=5572) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:00,234] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:37:00,236] {logging_mixin.py:115} INFO - [2024-02-21 05:37:00,236] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:00,239] {logging_mixin.py:115} INFO - [2024-02-21 05:37:00,238] {dagbag.py:300} INFO - File /opt/airflow/dags/tests/test_models.py assumed to contain no DAGs. Skipping.
[2024-02-21 05:37:00,239] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:00,260] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.036 seconds
[2024-02-21 05:37:06,328] {processor.py:153} INFO - Started process (PID=5574) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:06,329] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:37:06,330] {logging_mixin.py:115} INFO - [2024-02-21 05:37:06,330] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:06,332] {logging_mixin.py:115} INFO - [2024-02-21 05:37:06,332] {dagbag.py:300} INFO - File /opt/airflow/dags/tests/test_models.py assumed to contain no DAGs. Skipping.
[2024-02-21 05:37:06,333] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:06,362] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.040 seconds
[2024-02-21 05:37:37,165] {processor.py:153} INFO - Started process (PID=5637) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:37,167] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:37:37,168] {logging_mixin.py:115} INFO - [2024-02-21 05:37:37,167] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:37,169] {logging_mixin.py:115} INFO - [2024-02-21 05:37:37,169] {dagbag.py:300} INFO - File /opt/airflow/dags/tests/test_models.py assumed to contain no DAGs. Skipping.
[2024-02-21 05:37:37,169] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:37:37,183] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.022 seconds
[2024-02-21 05:38:07,990] {processor.py:153} INFO - Started process (PID=5700) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:38:07,992] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:38:07,993] {logging_mixin.py:115} INFO - [2024-02-21 05:38:07,993] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:38:07,996] {logging_mixin.py:115} INFO - [2024-02-21 05:38:07,996] {dagbag.py:300} INFO - File /opt/airflow/dags/tests/test_models.py assumed to contain no DAGs. Skipping.
[2024-02-21 05:38:07,996] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:38:08,013] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.030 seconds
[2024-02-21 05:38:38,747] {processor.py:153} INFO - Started process (PID=5753) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:38:38,751] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:38:38,752] {logging_mixin.py:115} INFO - [2024-02-21 05:38:38,752] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:38:38,753] {logging_mixin.py:115} INFO - [2024-02-21 05:38:38,753] {dagbag.py:300} INFO - File /opt/airflow/dags/tests/test_models.py assumed to contain no DAGs. Skipping.
[2024-02-21 05:38:38,754] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:38:38,777] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.036 seconds
[2024-02-21 05:39:08,981] {processor.py:153} INFO - Started process (PID=5816) to work on /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:39:08,983] {processor.py:641} INFO - Processing file /opt/airflow/dags/tests/test_models.py for tasks to queue
[2024-02-21 05:39:08,984] {logging_mixin.py:115} INFO - [2024-02-21 05:39:08,984] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:39:08,985] {logging_mixin.py:115} INFO - [2024-02-21 05:39:08,985] {dagbag.py:300} INFO - File /opt/airflow/dags/tests/test_models.py assumed to contain no DAGs. Skipping.
[2024-02-21 05:39:08,985] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/test_models.py
[2024-02-21 05:39:08,997] {processor.py:161} INFO - Processing /opt/airflow/dags/tests/test_models.py took 0.020 seconds
